Concert page
Shakir-Hussain12/Capstone1 pull request #1
Opened 2023-01-04 17:12 UTC by Shakir-Hussain12

**For this PR, I**
---
- Set Up Linters and ESLint checks.
- Created & Styled the Index Page.
- Created & Styled the About Page.
- Used Javascript DOM to manipulate the navbar, features speakers, and programs section.
- Added 'Show More' & 'Show Less' buttons to featured speakers.
- Used Flexbox to maintain elements.
- Made both pages responsive for all screens.

2023-01-04 18:22 UTC, Gopxfs requested changes
# ♻️ STATUS: REQUIRED CHANGES ♻️

## Hi @Shakir-Hussain12 👋,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/l4JzhjVCQiWgeAOFa/giphy.gif">

## Highlights :rocket:
✔️ No linter errors.
✔️ Great code structure. Well done!
✔️ Nice theme!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🗒️  
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-04 18:22 UTC, Gopxfs commented on assets/stylesheets/style.css
> +}
To follow the original design, please make sure that your footer, in the mobile version of your homepage, has a white background:
![image](https://user-images.githubusercontent.com/42799579/210621480-e8b2605f-b3fe-4b0c-8b98-1026c66ec2b4.png)

2023-01-04 18:22 UTC, Gopxfs commented on assets/stylesheets/style.css
> +}
As requested in the project requirements:
![image](https://user-images.githubusercontent.com/42799579/210622178-11fd3e5e-92f1-474c-8a42-f571aafb2b75.png)

Please make sure to follow the original design colors. Keep in mind that your webpage doesn't need to be identical, but remember that you are following design guidelines! This project's goal is to improve your ability to follow design guidelines (imagine Microverse as a client requesting a website) 😉. 

For this reason, kindly remove the gradients from the headers and update it background colors to look accordingly to the original idea:

Your design:
![image](https://user-images.githubusercontent.com/42799579/210622442-e57a4548-93b5-4daa-9865-531117d42df7.png)

- Top header: black gradient background and black text
- Bottom header: yellow gradient background

Original design:
![image](https://user-images.githubusercontent.com/42799579/210622563-7e6d2084-3a97-46cb-8b48-7b8d68473384.png)

- [ ] Top header: solid black background and white text
- [ ] Bottom header: solid white background

2023-01-04 18:22 UTC, Gopxfs commented
https://github.com/Shakir-Hussain12/Capstone1/blob/concert-page/README.md?plain=1#L112-L114

As requested on the project requirements: 
![image](https://user-images.githubusercontent.com/42799579/203677075-bbd40833-374d-4f69-b46f-81fe4d5b9324.png) 

You should add a link to your video presenting the project on this PR 😉. Currently, you have a Loom video presenting your Portfolio project, instead of the capstone.

2023-01-04 18:22 UTC, Gopxfs commented
https://github.com/Shakir-Hussain12/Capstone1/blob/concert-page/README.md?plain=1#L239-L245

As requested in the project requirements:  
![image](https://user-images.githubusercontent.com/42799579/203677364-a4f79c4a-ebf5-467a-b9c4-e22103c2cc57.png)  

Please make sure to give credit to the [original author](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) of the design 😉.  
> Note: the credits should be in the `Acknowledgments` section

2023-01-04 18:22 UTC, Gopxfs commented
https://github.com/Shakir-Hussain12/Capstone1/blob/concert-page/README.md?plain=1#L265-L270

Make sure to add the corresponding path to your MIT since it isn't working: :wink:: 
![image](https://user-images.githubusercontent.com/42799579/210262542-c41ce04e-2721-419c-a3da-c107a91e88ed.png)

> Please remove all the empty sections from your `README` file!

2023-01-05 06:14 UTC, Kossi-stack approved these changes
## Status: Approved ✔️

**Hi @Shakir-Hussain12,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 

![128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c](https://user-images.githubusercontent.com/81444338/150871274-7d1b779c-88e6-420b-a530-b7b905eaa3ac.gif)

You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-01-05 07:55 UTC, merged